server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.126.128:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ROOT
  # Redis的相关配置
  data:
    redis:
      host: 192.168.126.128
      port: 6379
#  password: 1234

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /v3/api-docs/**x`
#      - /admin/product/category/download
minio:
  endpoint: http://192.168.126.128:9000
  username: admin
  password: admin123456
  bucketName: spzx-bucket # 最好是先去创建这个bucket

